AWSTemplateFormatVersion: "2010-09-09"

Description: AWS Elastic Container Service (ECS) task and service definitions for TinyDevCRM

Parameters:
  ApplicationDockerImageTag:
    Type: String
    Default: latest
    Description: Image tag for the Django application backend Docker build.

  ApplicationECRRepositoryName:
    Type: String
    Default: tinydevcrm-ecr/app
    Description: Elastic Container Registry repository name where Docker builds for the Django application backend go.

  ECSClusterReference:
    Type: String
    Default: tinydevcrm-ec2-compute-ecs-cluster
    Description: CloudFormation output reference from stack `aws-ec2-compute.yaml` for the ECS cluster.

Resources:
