AWSTemplateFormatVersion: "2010-09-09"

Description: AWS Elastic Container Service (ECS) task and service definitions for TinyDevCRM

Parameters:
  ApplicationDockerImageTag:
    Type: String
    Default: latest
    Description: Image tag for the Django application backend Docker image.

  DatabaseDockerImageTag:
    Type: String
    Default: latest
    Description: Image tag for the PostgreSQL database Docker image.

  ApplicationECRRepositoryName:
    Type: String
    Default: tinydevcrm-ecr/app
    Description: Elastic Container Registry repository name where Docker builds for the Django application backend go.

  ECSClusterReference:
    Type: String
    Default: tinydevcrm-ec2-compute-ecs-cluster
    Description: CloudFormation output reference from stack `aws-ec2-compute.yaml` for the ECS cluster.

Resources:
  ApplicationTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: tinydevcrm-app
      Volumes:
        - Name: static_volume
          Host:
            SourcePath: /home/app/web/staticfiles
      ContainerDefinitions:
        - Name: tinydevcrm-app
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/tinydevcrm-ecr/app:${ApplicationDockerImageTag}
          MemoryReservation: 395
          Cpu: 245
          MountPoints:
            - SourceVolume: static_volume
              ContainerPath: /home/app/web/staticfiles
