AWSTemplateFormatVersion: "2010-09-09"

Description: AWS Elastic Container Register (ECR) repository definitions for TinyDevCRM.

Resources:
  DjangoBackendRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: tinydevcrm-ecr/app
      RepositoryPolicyText:
        Statement:
          - Sid: RemoteAccountAccess
            Effect: Allow
            Principal:
              AWS: "arn:aws:iam:158949774536:root"
              Service: codebuild.amazonaws.com
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
        Version: "2008-10-17"

  NginxRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: tinydevcrm-ecr/nginx

  PostgreSQLDatabaseRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: tinydevcrm-ecr/db