AWSTemplateFormatVersion: "2010-09-09"

Description: AWS Elastic Container Service (ECS) task and service definitions for TinyDevCRM

Parameters:
  ApplicationDockerImageTag:
    Type: String
    Default: latest
    Description: Image tag for the Django application backend Docker image.

  ApplicationECRRepositoryName:
    Type: String
    Default: tinydevcrm-ecr/app
    Description: Elastic Container Registry repository name where Docker builds for the Django application backend go.

  DatabaseDockerImageTag:
    Type: String
    Default: latest
    Description: Image tag for the PostgreSQL database Docker image.

  ECSClusterName:
    Type: String
    Default: tinydevcrm-ecs-cluster
    Description: "ECS cluster name matching the one defined in 'aws-ec2-compute.yaml'."

  PublicLoadBalancerReference:
    Type: String
    Default: tinydevcrm-ec2-compute-public-elb
    Description: "CloudFormation ARN output reference from stack `aws-ec2-compute.yaml` for the public load balancer."

  VPCReference:
    Type: String
    Default: tinydevcrm-ec2-networking-vpc
    Description: "Reference to VPC deployed as part of stack `tinydevcrm-ec2-networking.yaml`."

Resources:
  ApplicationCluster:
    Type: "AWS::ECS::Cluster"
    Description: ECS cluster for deploying ECS task and service definitions.
    Properties:
      ClusterName: !Sub ${ECSClusterName}

  ApplicationService:
    Type: "AWS::ECS::Service"
    DependsOn:
      - ApplicationLoadBalancerHttpListener
    Properties:
      Cluster: !Ref ApplicationCluster
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: 1
      LoadBalancers:
        - ContainerName: tinydevcrm-app
          ContainerPort: 8000
          TargetGroupArn: !Ref ApplicationServiceTargetGroup
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.amazonaws.com/AWSServiceRoleForECS"
      TaskDefinition: !Ref ApplicationTaskDefinition

  ApplicationTaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      ContainerDefinitions:
        - Name: tinydevcrm-app
          Command:
            - gunicorn
            - "wsgi:application"
            - "--bind"
            - "0.0.0.0:8000"
          Cpu: 245
          Environment:
            - Name: DJANGO_SETTINGS_MODULE
              Value: app.src.core.settings
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/tinydevcrm-ecr/app:${ApplicationDockerImageTag}"
          MemoryReservation: 395
          MountPoints:
            - ContainerPath: /home/app/web/staticfiles
              SourceVolume: static_volume
          PortMappings:
            - ContainerPort: 8000
        - Name: collectstatic
          Command:
            - python3
            - manage.py
            - collectstatic
            - "--no-input"
          Cpu: 5
          Environment:
            - Name: DJANGO_SETTINGS_MODULE
              Value: app.src.core.settings
          Essential: false
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/tinydevcrm-ecr/app:${ApplicationDockerImageTag}"
          MemoryReservation: 5
          MountPoints:
            - ContainerPath: /home/app/web/staticfiles
              SourceVolume: static_volume
      Family: tinydevcrm-app
      Volumes:
        - Name: static_volume
          Host:
            SourcePath: /home/app/web/staticfiles