AWSTemplateFormatVersion: "2010-09-09"

Description: Data layer for database and application for TinyDevCRM. This is necessary in order to avoid tying data with compute layer lifecycles (such as deletion). EBS for database persist files, and EFS for static files. Called persist in order to avoid fat-fingering with `db.yaml` and associated db app lifecycles.

Resources:
  DatabaseBlockStore:
    Type: "AWS::EC2::Volume"
    Properties:
      AvailabilityZone: !Select
        - 0
        - "Fn::GetAZs": ""
      Size: 1
      Tags:
        - Key: Name
          Value: tinydevcrm-db-ebs
      VolumeType: gp2

  ApplicationFileStore:
    Type: "AWS::EFS::FileSystem"
    Description: NOTE that the name of the application file store has to be pre-pended with a '/' character if the rex-ray efs driver is to discover the NFS drive properly with autoprovisioning turned off. Otherwise, the ECS service will hang and fail silently, with logs available in the ECS task definition only.
    Properties:
      FileSystemTags:
        - Key: Name
          Value: /tinydevcrm-app-efs
